# Create the /nfs on your serveur
# $ mkdir /nfs
# $ chmod 777 /nfs
# Add in the file /etc/exports
# /nfs *(rw,sync,root_squash,no_subtree_check)
# systemctl enable nfs-server.service --now
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-storage-provisioner-system
  namespace: argo-cd
spec:
  destination:
    namespace: nfs-exporter-system
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    helm:
      parameters:
        - name: nfs.path
          value: /nfs
        - name: storageClass.name
          value: nfs
        - name: nfs.server
          value: 192.168.122.114
    repoURL: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner'
    targetRevision: 4.0.13
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
