apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connaisseur
  namespace: argo-cd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: connaisseur
  source:
    chart: connaisseur
    repoURL: 'https://sse-secure-systems.github.io/connaisseur/charts'
    targetRevision: 1.4.3
    helm:
      parameters:
        - name: deployment.replicasCount
          value: '1'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
