# Cf: https://github.com/neuvector/prometheus-exporter
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neuvector-monitor
  namespace: argo-cd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: neuvector
  project: default
  source:
    chart: monitor
    repoURL: 'https://neuvector.github.io/neuvector-helm/'
    targetRevision: 2.2.2
    helm:
      parameters:
        - name: registry
          value: docker.io
        - name: exporter.enabled
          value: 'true'
        - name: exporter.CTRL_USERNAME
          value: admin
        - name: exporter.CTRL_PASSWORD
          value: admin
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true