apiVersion: v1
kind: Service
metadata:
  name: neuvector-metrics
  namespace: neuvector
  labels:
    app: neuvector-prometheus-exporter
spec:
  selector:
    app: neuvector-prometheus-exporter-pod
  ports:
    - name: http-metrics
      protocol: TCP
      port: 8068
      targetPort: 8068
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: neuvector
  namespace: neuvector
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: neuvector-prometheus-exporter
  # namespaceSelector:
  #   matchNames:
  #   - neuvector
  endpoints:
  - port: http-metrics
