# Cf https://linkerd.io/2.11/tasks/install-helm/
#########################################################
# This file is not used, please edit install.sh instead #
#########################################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argo-cd
spec:
  destination:
    namespace: linkerd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: linkerd2
    repoURL: 'https://helm.linkerd.io/stable'
    targetRevision: 2.11.4
