apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loft
  namespace: argo-cd
spec:
  destination:
    namespace: loft
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: loft
    repoURL: 'https://charts.loft.sh'
    targetRevision: 2.1.6
    helm:
      parameters:
        - name: admin.email
          value: admin@xxx.com
        - name: admin.password
          value: admin
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

