apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-demo
  namespace: argo-cd
spec:
  destination:
    namespace: rancher-demo
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/gigi206/k8s'
    path: argocd/rancher-demo/rancher-demo/charts/rancher-demo-helm/0.2.0
    # repoURL: 'https://gitlab.com/bdekany/rancher-demo.git'
    # path: charts/rancher-demo-helm/0.2.0
    # repoURL: 'https://gitlab.com/monachus/channel.git'
    # path: /resources/2020-01-07-using-metallb-with-rancher/deploy/3-demo
    targetRevision: HEAD
    helm:
      parameters:
        - name: replicaCount
          value: '2'
        - name: ingress.host
          value: rancher-demo.gigix
        - name: ingress.enabled
          value: 'true'
        - name: ingress.className
          value: nginx
        #- name: autoscaling.enabled
        #  value: 'true'
        # - name: ingress.annotations.argocd\.argoproj\.io/sync-options
        #   value: SkipDryRunOnMissingResource=true
        # - name: ingress.annotations.argocd\.argoproj\.io/sync-options
        #   value: PrunePropagationPolicy=orphan
        # - name: service.type
        #   value: LoadBalancer
        - name: cow_color
          value: green
        #- name: >-
        #    affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector.matchExpressions[0].key
        #  value: app.kubernetes.io/instance
        #- name: >-
        #    affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector.matchExpressions[0].operator
        #  value: In
        #- name: >-
        #    affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector.matchExpressions[0].values[0]
        #  value: rancher-demo
        #- name: >-
        #    affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey
        #  value: kubernetes.io/hostname
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
