apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argo-cd
spec:
  destination:
    namespace: loki-stack
    name: in-cluster
    # server: 'https://kubernetes.default.svc'
  source:
    chart: loki-stack
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: '2.6.5'
    helm:
      parameters:
        # - name: loki.config.auth_enabled
        #   value: 'true'
        - name: loki.persistence.enabled
          value: 'true'
        - name: loki.persistence.storageClassName
          value: longhorn
        - name: loki.persistence.size
          value: 5Gi
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
