apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argo-cd
spec:
  destination:
    namespace: rook-ceph
    name: in-cluster
    # server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://charts.rook.io/release'
    targetRevision: v1.9.9
    chart: rook-ceph
    helm:
      values: |
        crds:
          enabled: true
        currentNamespaceOnly: true
        # enablePluginSelinuxHostMount: true
        # enableCSIEncryption: true
        provisionerReplicas: 1
        csi:
          enableGrpcMetrics: false
        monitoring:
          enabled: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
