apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-repository-manager
  namespace: argo-cd
spec:
  destination:
    namespace: nexus-repository-manager
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: nexus-repository-manager
    repoURL: 'https://sonatype.github.io/helm3-charts/'
    targetRevision: 35.0.0
    helm:
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hostRepo
          value: nexus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
