# ARP: https://gitlab.com/monachus/channel/-/tree/master/resources/2021-09-07-ha-rke2-kube-vip-rancher
# Youtube: https://www.youtube.com/watch?v=QqSgiezqMAA
# BGP: https://anywhere.eks.amazonaws.com/docs/tasks/workload/loadbalance/kubevip/bgp/
# ARP: https://anywhere.eks.amazonaws.com/docs/tasks/workload/loadbalance/kubevip/arp/

# https://github.com/kube-vip/helm-charts/blob/main/charts/kube-vip/templates/daemonset.yaml
# export VIP=191.168.122.200
# export TAG=latest
# export INTERFACE=ens18
# export CONTAINER_RUNTIME_ENDPOINT=unix:///run/k3s/containerd/containerd.sock
# export CONTAINERD_ADDRESS=/run/k3s/containerd/containerd.sock
# crictl pull docker.io/plndr/kube-vip:$TAG
# alias kube-vip="ctr --namespace k8s.io run --rm --net-host docker.io/plndr/kube-vip:$TAG vip /kube-vip"
# kube-vip manifest daemonset \
#     --arp \
#     --interface $INTERFACE \
#     --address $VIP \
#     --controlplane \
#     --leaderElection \
#     --taint \
#     --services \
#     --inCluster

# test
#kubectl create deploy nginx --image=nginx:stable-alpine
#kubectl expose deploy nginx --port=80 --type=LoadBalancer
#kubectl get services


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevip
  namespace: argo-cd
spec:
  destination:
    namespace: kubevip-system
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: kube-vip
    repoURL: 'https://kube-vip.io/helm-charts'
    targetRevision: 0.4.1
    helm:
      parameters:
        - name: env.address
          value: 192.168.122.200
        - name: env.vip_arp
          value: "true"
        - name: env.port
          value: "6443"
        - name: env.vip_interface
          value: eth1
        - name: env.vip_cidr
          value: "32"
        #- name: env.cp_enable
        #  value: "true"
        - name: env.cp_namespace
          value: kubevip-system
        - name: env.vip_ddns
          value: "false"
        - name: env.svc_enable
          value: "true"
        - name: env.vip_leaderelection
          value: "true"
        - name: env.vip_leaseduration
          value: "5"
        - name: env.vip_renewdeadline
          value: "3"
        - name: env.vip_retryperiod
          value: "1"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
