# Utiliser les parameter afin qu'il récupère dynamiquement le nom du repo
# Utiliser les WorflowTemplate:
# - builder conteneur avec buildah et envoyer conteneur dans harbor
# - deployer conteneur dans k8s
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: demo-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: demo
  arguments:
    parameters:
      - name: repo
        value: null
  templates:
  - name: demo
    inputs:
      artifacts:
      - name: source
        path: /src
        git:
          repo: https://<url interne gitea kubernetes>
          revision: "master"
      # - name: objects
      #   path: /s3
      #   s3:
      #     endpoint: storage.googleapis.com
      #     bucket: my-bucket-name
      #     key: path/in/bucket
      #     accessKeySecret:
      #       name: my-s3-credentials
      #       key: accessKey
      #     secretKeySecret:
      #       name: my-s3-credentials
      #       key: secretKey
    container:
      image: debian
      command: [sh, -c]
      args: ["ls -l /src /bin/kubectl /s3"]