apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-external-snapshotter
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kubernetes-csi/external-snapshotter/'
    path: client/config/crd
    targetRevision: v4.2.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
