apiVersion: v1
kind: Namespace
metadata:
  name: crunchy-postgres-olm-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: crunchy-postgres-olm-operator
spec:
  targetNamespaces:
  - crunchy-postgres-olm-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: crunchy-postgres
  namespace: crunchy-postgres-olm-operator
spec:
  channel: v5
  name: postgresql
  source: operatorhubio-catalog
  sourceNamespace: operator-lifecycle-manager