# Please read https://thenewstack.io/tutorial-installing-and-configuring-minio-as-a-model-registry-on-rke2/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argo-cd
spec:
  destination:
    namespace: hello-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hosts[0].host
          value: hello.gigix
        - name: ingress.hosts[0].paths[0].path
          value: /
        - name: ingress.hosts[0].paths[0].pathType
          value: ImplementationSpecific
    path: helm
    # Custom repo must be created first with "Skip server verification" checked
    repoURL: https://gitlab.gitlab.gigix/demo/container.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true