apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-ca-tls
  namespace: gitlab
spec:
  secretName: gitlab-tls-ca-key-pair
  #duration: 2160h # 90d
  #renewBefore: 360h # 15d
  isCA: true
  issuerRef:
    #name: selfsigned-issuer
    #kind: Issuer
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  #commonName: "gitlab.gigix"
  #commonName: "gitlab.gitlab.gigix"
  dnsNames:
  - '*.gitlab.gigix'
  #- gitlab.gitlab.gigix
