apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-lifecycle-manager
  namespace: argo-cd
spec:
  destination:
    namespace: olm
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/operator-framework/operator-lifecycle-manager'
    path: deploy/chart
    targetRevision: v0.22.0
    helm:
      parameters:
        - name: catalog.replicaCount
          value: '1'
        - name: olm.replicaCount
          value: '1'
        # - name: monitoring.enabled
        #   value: 'true'
        # - name: monitoring.namespace
        #   value: prometheus-stack
        # - name: namespace
        #   value: operator-lifecycle-manager
        # - name: operator_namespace
        #   value: olm
        # - name: catalog_namespace
        #   value: operator-lifecycle-manager
        #   # value: operators
        # - name: replicaCount
        #   value: '2'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true