apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailhog
  namespace: argo-cd
spec:
  destination:
    namespace: mailhog
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: mailhog
    helm:
      parameters:
      - name: service.port.smtp
        value: "25"
    repoURL: https://codecentric.github.io/helm-charts
    targetRevision: 5.2.0
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
