apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argo-cd
spec:
  destination:
    namespace: metrics-server
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: metrics-server
    repoURL: 'https://kubernetes-sigs.github.io/metrics-server'
    targetRevision: 3.8.2
    helm:
      parameters:
        - name: replicas
          value: '1'
          # value: '3'
        - name: hostNetwork.enabled
          value: 'true'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
