apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost
  namespace: argo-cd
spec:
  destination:
    namespace: mattermost
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://helm.mattermost.com'
    targetRevision: 6.6.11
    chart: mattermost-team-edition
    helm:
      values: |
        persistence:
          data:
            enabled: 'true'
            size: 1Gi
            storageClass: longhorn
            accessMode: ReadWriteOnce
        plugins:
          enabled: 'true'
          size: 1Gi
          storageClass: longhorn
          accessMode: ReadWriteOnce
        mysql:
          enabled: 'true'
          mysqlRootPassword: "password"
          mysqlUser: "mattermost"
          mysqlPassword: "password"
          mysqlDatabase: mattermost
          persistence:
            enabled: true
            storageClass: "longhorn"
            accessMode: ReadWriteOnce
            size: 1Gi
        ingress:
          enabled: 'true'
          path: /
          annotations:
            certmanager.k8s.io/issuer:  selfsigned-cluster-issuer
            nginx.ingress.kubernetes.io/proxy-body-size: 50m
            nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            nginx.ingress.kubernetes.io/proxy-buffering: "on"
            nginx.ingress.kubernetes.io/configuration-snippet: |
              proxy_cache mattermost_cache;
              proxy_cache_revalidate on;
              proxy_cache_min_uses 2;
              proxy_cache_use_stale timeout;
              proxy_cache_lock on;
            #### To use the nginx cache you will need to set an http-snippet in the ingress-nginx configmap
            #### http-snippet: |
            ####     proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=mattermost_cache:10m max_size=3g inactive=120m use_temp_path=off;
          hosts:
            - mattermost.gigix
          tls:
            - secretName: mattermost-tls
              hosts:
                - mattermost.gigix
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
