apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argo-cd
spec:
  project: default
  destination:
    namespace: argo-workflows-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: '0.10.1'
    chart: argo-workflows
    helm:
      parameters:
        # - name: singleNamespace
        #   value: "true"
        # - name: workflow.serviceAccount.create
        #   value: "true"
        - name: controller.containerRuntimeExecutor
          value: emissary
        - name: server.ingress.enabled
          value: "true"
        - name: server.ingress.ingressClassName
          value: nginx
        - name:  >-
            server.ingress.annotations.cert-manager\.io/cluster-issuer
          value: selfsigned-cluster-issuer
        - name: server.secure
          value: "true"
        - name: server.ingress.hosts[0]
          value: argo-workflows.gigix
        - name: server.ingress.tls[0].secretName
          value: argoworkflows-tls
        - name: server.ingress.tls[0].hosts[0]
          value: argo-workflows.gigix
        - name: 'server.extraArgs[0]'
          value: '--auth-mode=server'
        # - name: 'server.extraArgs[0]'
        #   value: '--insecure-skip-server-verification'
        # - name: controller.metricsConfig.enabled
        #   value: "true"
        # - name: controller.persistence.archive
        #   value: "true"
        # - name: >-
        #     server.ingress.annotations.nginx\.ingress\.kubernetes\.io/auth-type
        #   value: basic
        # - name: >-
        #     server.ingress.annotations.nginx\.ingress\.kubernetes\.io/auth-secret
        #   value: basic-auth
        # - name: >-
        #     server.ingress.annotations.nginx\.ingress\.kubernetes\.io/auth-realm
        #   value: Authentication required
        - name: >-
            server.ingress.annotations.nginx\.ingress\.kubernetes\.io/backend-protocol
          value: https
        - name: >-
            server.ingress.annotations.nginx\.ingress\.kubernetes\.io/force-ssl-redirect
          value: "true"
        - name: >-
            server.ingress.annotations.ingress\.kubernetes\.io/rewrite-target
          value: /$2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
